# Rustfmt configuration for mimic
edition = "2021"
max_width = 100
use_small_heuristics = "Default"
fn_call_width = 80
struct_lit_width = 40
enum_variant_width = 40
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
reorder_imports = true
reorder_modules = true
format_code_in_doc_comments = true
use_field_init_shorthand = true
use_try_shorthand = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
